name: Deploy ECS Service Using AWS Copilot CLI
on:
  push:
    branches: ["develop"]

env:
  AWS_ACCOUNT_ID: "33333333333"
  AWS_REGION: "ap-southeast-1"
  ECS_SERVICE_NAME: "any-service"
  ECS_APP_NAME: "any-app"
  ENV: "any-env"

  GITHUB_SHA: ${{ github.sha }}

concurrency:
  group: ${{ github.ref }}

jobs:
  deploy:
    name: Deploy using Copilot
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github

      - name: Install Copilot CLI
        uses: ksivamuthu/aws-copilot-github-action@v0.0.8
        with:
          command: install

      - name: Rolling out new version
        run: |
          echo "application: ${{ env.ECS_APP_NAME }}" > copilot/.workspace
          copilot svc deploy --app ${{ env.ECS_APP_NAME }}  --name ${{ env.ECS_SERVICE_NAME }} --env ${{ env.ENV }} --tag ${{ env.GITHUB_SHA }}