services:
  qdrant:
    image: qdrant/qdrant:v1.11.4
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
      - 6335:6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage

configs:
  qdrant_config:
    content: |
      log_level: INFO