services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      MAX_ALLOWED_PACKET: 128M

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example