services:

  db:
    image: mariadb:11.4
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: synapsepassword

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
